- name: Install Apache
  apt:
    name: apache2
    state: present

- name: Deploy index.html
  template:
    src: index.html.j2
    dest: /var/www/html/index.html

- name: Enable and start Apache
  service:
    name: apache2
    state: started
    enabled: yes
